/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InvestingCalculatorsRouteImport } from './routes/investing-calculators'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksIndexRouteImport } from './routes/stocks.index'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalcTypeRouteImport } from './routes/_authenticated/calc.$type'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingCalculatorsRoute = InvestingCalculatorsRouteImport.update({
  id: '/investing-calculators',
  path: '/investing-calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIndexRoute = StocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StocksRoute,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => StocksRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalcTypeRoute = AuthenticatedCalcTypeRouteImport.update({
  id: '/calc/$type',
  path: '/calc/$type',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/investing-calculators': typeof InvestingCalculatorsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/stocks': typeof StocksRouteWithChildren
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/r/$slug': typeof RSlugRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks/': typeof StocksIndexRoute
  '/calc/$type': typeof AuthenticatedCalcTypeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/investing-calculators': typeof InvestingCalculatorsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/r/$slug': typeof RSlugRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks': typeof StocksIndexRoute
  '/calc/$type': typeof AuthenticatedCalcTypeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/investing-calculators': typeof InvestingCalculatorsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/stocks': typeof StocksRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/r/$slug': typeof RSlugRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks/': typeof StocksIndexRoute
  '/_authenticated/calc/$type': typeof AuthenticatedCalcTypeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/auth'
    | '/calculators'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/investing-calculators'
    | '/news'
    | '/privacy'
    | '/stocks'
    | '/terms'
    | '/dashboard'
    | '/r/$slug'
    | '/stocks/$symbol'
    | '/stocks/'
    | '/calc/$type'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/auth'
    | '/calculators'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/investing-calculators'
    | '/news'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/r/$slug'
    | '/stocks/$symbol'
    | '/stocks'
    | '/calc/$type'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai'
    | '/auth'
    | '/calculators'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/investing-calculators'
    | '/news'
    | '/privacy'
    | '/stocks'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/r/$slug'
    | '/stocks/$symbol'
    | '/stocks/'
    | '/_authenticated/calc/$type'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InvestingCalculatorsRoute: typeof InvestingCalculatorsRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  StocksRoute: typeof StocksRouteWithChildren
  TermsRoute: typeof TermsRoute
  RSlugRoute: typeof RSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing-calculators': {
      id: '/investing-calculators'
      path: '/investing-calculators'
      fullPath: '/investing-calculators'
      preLoaderRoute: typeof InvestingCalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/': {
      id: '/stocks/'
      path: '/'
      fullPath: '/stocks/'
      preLoaderRoute: typeof StocksIndexRouteImport
      parentRoute: typeof StocksRoute
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof StocksRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calc/$type': {
      id: '/_authenticated/calc/$type'
      path: '/calc/$type'
      fullPath: '/calc/$type'
      preLoaderRoute: typeof AuthenticatedCalcTypeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCalcTypeRoute: typeof AuthenticatedCalcTypeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCalcTypeRoute: AuthenticatedCalcTypeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface StocksRouteChildren {
  StocksSymbolRoute: typeof StocksSymbolRoute
  StocksIndexRoute: typeof StocksIndexRoute
}

const StocksRouteChildren: StocksRouteChildren = {
  StocksSymbolRoute: StocksSymbolRoute,
  StocksIndexRoute: StocksIndexRoute,
}

const StocksRouteWithChildren =
  StocksRoute._addFileChildren(StocksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  CalculatorsRoute: CalculatorsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  InvestingCalculatorsRoute: InvestingCalculatorsRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  StocksRoute: StocksRouteWithChildren,
  TermsRoute: TermsRoute,
  RSlugRoute: RSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
